# Generated by Django 5.1.3 on 2024-11-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, choices=[('A1', '联盟一区'), ('A2', '联盟二区'), ('A3', '联盟三区'), ('A4', '联盟四区'), ('A5', '联盟五区'), ('IONIA', '艾欧尼亚'), ('ROSE', '黑色玫瑰'), ('SUMMITS', '峡谷之巅')], max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tier',
            field=models.CharField(blank=True, choices=[('IRON', '坚韧黑铁'), ('BRONZE', '英勇黄铜'), ('SILVER', '不屈白银'), ('GOLD', '荣耀黄金'), ('PLATINUM', '华贵铂金'), ('EMERALD', '流光翡翠'), ('DIAMOND', '璀璨钻石'), ('MASTER', '超凡大师'), ('GRANDMASTER', '傲世宗师'), ('CHALLENGER', '最强王者')], max_length=12),
        ),
    ]
